//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors()
        {
            this.Appointment = new HashSet<Appointment>();
            this.DocResearch = new HashSet<DocResearch>();
        }
    
        public int IDDoc { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int IDSpecialization { get; set; }
        public int IDSector { get; set; }
        public int IDSeparation { get; set; }
        public int Cabinet { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int valuable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocResearch> DocResearch { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Separation Separation { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
