//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SickList
    {
        public int IDSickList { get; set; }
        public int IDDisease { get; set; }
        public Nullable<System.DateTime> SlOpen { get; set; }
        public Nullable<System.DateTime> SlClose { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Disease Disease1 { get; set; }
    }
}
